#!/usr/bin/env python
"""Render a translated Markdown paper to PDF.

Pipeline: Markdown --pandoc--> self-contained HTML --Chrome/Edge--> PDF

Images are embedded as data URIs by pandoc, so the PDF never depends on
the figures folder staying next to the Markdown. Chrome supplies the CJK
font rendering and page breaking, so no LaTeX install is required.

A 目录 page is generated by default, plus a PDF outline (the bookmark tree
Acrobat and every viewer's sidebar show) built from the headings. The two are
independent: the TOC page is printed text, the outline is real navigation.
Note that Chrome does not turn in-page anchors into PDF link annotations, so
the TOC page lists sections but is not clickable - the outline is what you
navigate with.

If the Markdown already carries an add_toc.py block, it is stripped before
rendering so the PDF never shows two tables of contents.

Usage:
    python md_to_pdf.py <input.md> [-o out.pdf] [--font serif|sans]
                        [--no-toc] [--toc-depth 3]

Exit codes:
    0  PDF written and verified
    1  error (missing pandoc / no browser / render failed)
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

BROWSERS = [
    # Windows
    r"C:\Program Files\Google\Chrome\Application\chrome.exe",
    r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
    r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
    r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
    # macOS
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
    "/Applications/Chromium.app/Contents/MacOS/Chromium",
    # Linux
    "/usr/bin/google-chrome",
    "/usr/bin/chromium-browser",
    "/usr/bin/chromium",
    "/usr/bin/microsoft-edge",
]

# Latin faces come first on purpose. Chrome resolves font-family per
# character, so ASCII, digits and ASCII punctuation - ( ) [ ] - , . % - are
# taken from Times New Roman, and only the CJK codepoints fall through to the
# Han font behind it. Putting the Han font first would hand every digit and
# bracket to SimSun's typewriter-ish Latin glyphs, which is what makes a
# machine-translated paper look homemade.
#
# Fullwidth Chinese punctuation （），。「」 lives only in the Han font, so it
# stays Chinese no matter what leads the stack - which is correct typography;
# Times New Roman has no fullwidth forms to offer.
LATIN = '"Times New Roman", Times, "Liberation Serif"'
# 宋体 for running text, 黑体 for headings. SimSun/SimHei are the literal
# Chinese names; the rest are the macOS and Linux equivalents so the same CSS
# survives off Windows.
SONG = 'SimSun, "Songti SC", "Source Han Serif SC", "Noto Serif CJK SC", serif'
HEI = ('SimHei, "Heiti SC", "Microsoft YaHei", "Source Han Sans SC", '
       '"Noto Sans CJK SC", sans-serif')

FONTS = {
    "serif": f'{LATIN}, {SONG}',      # 正文：中文宋体 + 拉丁 Times
    "sans": f'{LATIN}, {HEI}',        # 正文改黑体，拉丁仍 Times
}
HEAD_FONT = f'{LATIN}, {HEI}'         # 题头：中文黑体加粗 + 拉丁 Times

CSS = """
@page {{ size: A4; margin: 20mm 18mm; }}
body {{
  font-family: {body_font};
  font-size: 10.5pt; line-height: 1.75; color: #1a1a1a;
  max-width: none; margin: 0;
  text-align: justify;
}}
h1 {{ font-family: {head_font}; font-size: 19pt; font-weight: 700;
     line-height: 1.4;
     margin: 0 0 1.2em; padding-bottom: .4em; border-bottom: 2px solid #333; }}
h2 {{ font-family: {head_font}; font-size: 14pt; font-weight: 700;
     margin: 1.8em 0 .7em;
     padding-left: .5em; border-left: 4px solid #333; break-after: avoid; }}
h3 {{ font-family: {head_font}; font-size: 11.5pt; font-weight: 700;
     margin: 1.3em 0 .5em; break-after: avoid; }}
p {{ margin: 0 0 .8em; }}

/* The Markdown supplies its own H1; pandoc's metadata title would duplicate it */
h1.title, header#title-block-header {{ display: none; }}

/* implicit_figures turns "![caption](img)" into figure+figcaption, which is
   the only reliable way to stop a page break landing between a figure and
   its caption - and a caption printed under the wrong figure is worse than
   no caption at all. */
figure {{ break-inside: avoid; page-break-inside: avoid; margin: 1.4em 0; }}
/* Cap the image height so image + caption still fit one page. break-inside is
   only honoured while the block fits; a tall portrait figure (a 951x1373 plot
   plus a five-line caption) overflows the page box, Chrome gives up, and the
   caption lands alone on the next page under nothing. */
figure img {{ margin: 0 auto .5em; max-height: 72vh; width: auto; }}
/* Captions are translated prose, so they follow the body rule: 中文宋体,
   Latin and digits Times. Stated explicitly rather than left to inherit,
   because the caption is the one place a reader compares Chinese against the
   figure's own English labels. */
figcaption {{ font-family: {body_font}; font-size: 9pt; line-height: 1.65;
             color: #2a2a2a; text-align: left; }}
img {{ max-width: 100%; height: auto; display: block; margin: .8em auto; }}

blockquote {{
  background: #f6f7f9; border-left: 3px solid #8a8f98;
  margin: 0 0 1.4em; padding: .8em 1em; font-size: 9.5pt;
  break-inside: avoid; text-align: left;
}}
blockquote p {{ margin: .25em 0; }}

table {{ border-collapse: collapse; width: 100%; font-size: 9pt;
        margin: 1em 0; break-inside: avoid; }}
th, td {{ border: 1px solid #c8ccd2; padding: .4em .6em; text-align: left; }}
th {{ background: #eef0f3; font-family: {head_font}; }}

code {{ font-family: Consolas, "Courier New", monospace; font-size: 9pt;
       background: #f0f1f3; padding: .1em .35em; border-radius: 3px; }}
/* Fenced blocks stay monospace even though the body is Times: this skill
   writes display formulas as ASCII art, and the sum limits above and below
   the ∑ only line up in a fixed-width face. */
pre {{ background: #f6f7f9; padding: .8em; overflow-x: auto;
      border-radius: 4px; break-inside: avoid; }}
pre code {{ background: none; padding: 0; }}

/* Reference lists: dense, left-aligned, English */
ol {{ padding-left: 1.6em; }}
ol li {{ margin-bottom: .3em; font-size: 9.5pt; text-align: left; }}

hr {{ border: none; border-top: 1px solid #d5d8dd; margin: 2em 0; }}
a {{ color: #1a4d8f; text-decoration: none; word-break: break-all; }}
em {{ color: #555; }}

/* Table of contents. Sits on the title page and pushes the body to a fresh
   page, the way a paper's front matter reads. */
nav#TOC {{ break-after: page; page-break-after: always;
          font-size: 10pt; line-height: 1.9; text-align: left; }}
nav#TOC ul {{ list-style: none; margin: 0; padding-left: 0; }}
nav#TOC ul ul {{ padding-left: 1.4em; font-size: 9.5pt; }}
/* The document's own H1 is the outermost TOC entry with every section nested
   under it. Hide that one link and lift its children to flush left. */
nav#TOC > ul > li > a {{ display: none; }}
nav#TOC > ul > li > ul {{ padding-left: 0; font-size: 10pt; }}
nav#TOC a {{ color: #1a1a1a; }}
nav#TOC ul ul a {{ color: #3a3a3a; }}
"""

# add_toc.py's block, delimited so it can be refreshed in place. Pandoc gets
# its own --toc, so this one is dropped on the way in; otherwise the PDF opens
# with two tables of contents.
MD_TOC_BLOCK = re.compile(r"^<!-- TOC -->.*?^<!-- /TOC -->\n?",
                          re.S | re.M)

# A leaf TOC entry pointing at a figure heading. The link text carries no tags
# ([^<]* cannot cross into a nested <ul>), so this only ever matches childless
# entries - it can never swallow a section that has subsections under it.
TOC_FIGURE_ENTRY = re.compile(
    r'<li><a href="#[^"]*" id="toc-[^"]*">\s*'
    r'(?:图|表|Figure|Table|Fig\.?|附图|补充图)\s*\d[^<]*</a></li>\s*',
    re.I)

TOC_NAV = re.compile(r'<nav id="TOC".*?</nav>\s*', re.S)


def strip_md_toc(text: str) -> tuple:
    """Remove an add_toc.py block. Returns (text, was_present)."""
    out, n = MD_TOC_BLOCK.subn("", text)
    return out, bool(n)


def tidy_toc(html: str) -> tuple:
    """Drop figure entries from pandoc's nav and move it below the title.

    Figure headings are H3, so a depth-3 TOC would otherwise list a dozen
    caption titles and bury the actual sections. Pandoc also emits the nav as
    the first thing in <body>, i.e. above the paper's own H1; a table of
    contents belongs after the title.

    It goes immediately before the first section heading - the same place
    add_toc.py puts its block - so the title AND the author line stay together
    on the front page. Landing it right after </h1> would push the authors
    past the TOC and, with break-after:page, onto page two.

    Returns (html, entries_kept, figure_entries_dropped).
    """
    nav_match = TOC_NAV.search(html)
    if not nav_match:
        return html, 0, 0
    nav = nav_match.group(0)

    nav, dropped = TOC_FIGURE_ENTRY.subn("", nav)
    nav = re.sub(r"<ul>\s*</ul>", "", nav)               # emptied sublists
    kept = len(re.findall(r'<li><a href="#', nav))

    rest = html[:nav_match.start()] + html[nav_match.end():]
    anchor = re.search(r"<h2[ >]", rest) or re.search(r"</h1>", rest)
    if not anchor:                                       # leave it where it is
        return (html[:nav_match.start()] + nav + html[nav_match.end():],
                kept, dropped)
    at = anchor.start() if anchor.re.pattern.startswith("<h2") else anchor.end()
    return rest[:at] + nav + rest[at:], kept, dropped


def find_browser():
    for p in BROWSERS:
        if os.path.exists(p):
            return p
    for name in ("chrome", "google-chrome", "chromium", "msedge",
                 "microsoft-edge"):
        p = shutil.which(name)
        if p:
            return p
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("md")
    ap.add_argument("-o", "--out")
    ap.add_argument("--font", choices=("serif", "sans"), default="serif",
                    help="body typeface; headings always use the sans stack")
    ap.add_argument("--keep-html", action="store_true",
                    help="keep the intermediate HTML for debugging")
    ap.add_argument("--no-toc", dest="toc", action="store_false",
                    help="skip the 目录 page and the PDF outline")
    ap.add_argument("--toc-depth", type=int, default=3, metavar="N",
                    help="deepest heading level in the 目录 (default 3; "
                         "图/表 headings are excluded either way)")
    args = ap.parse_args()

    md = Path(args.md).resolve()
    if not md.exists():
        print(f"ERROR: not found: {md}", file=sys.stderr)
        return 1

    out = Path(args.out).resolve() if args.out else md.with_suffix(".pdf")

    if not shutil.which("pandoc"):
        print("ERROR: pandoc not found. https://pandoc.org/installing.html",
              file=sys.stderr)
        return 1
    browser = find_browser()
    if not browser:
        print("ERROR: no Chrome/Edge found for PDF rendering.", file=sys.stderr)
        return 1

    tmp = Path(tempfile.mkdtemp(prefix="md2pdf_"))
    css_file = tmp / "style.css"
    css_file.write_text(
        CSS.format(body_font=FONTS[args.font], head_font=HEAD_FONT),
        encoding="utf-8")
    html = (md.with_suffix(".html") if args.keep_html else tmp / "doc.html")

    # add_toc.py's block would collide with pandoc's --toc, so feed pandoc a
    # copy without it. The user's file is never touched.
    src_text = md.read_text(encoding="utf-8")
    stripped, had_md_toc = strip_md_toc(src_text)
    src = md
    if had_md_toc:
        src = tmp / md.name
        with open(src, "w", encoding="utf-8", newline="\n") as f:
            f.write(stripped)

    # Markdown -> self-contained HTML (images become data URIs).
    # pagetitle, not title: title makes pandoc emit a <header> block that the
    # CSS hides but Chrome still picks up as the first PDF bookmark.
    cmd = [
        "pandoc", str(src), "-f", "gfm+implicit_figures", "-t", "html5",
        "--standalone", "--embed-resources", "--css", str(css_file),
        "--metadata", f"pagetitle={md.stem}",
        "--resource-path", str(md.parent),
        "-o", str(html),
    ]
    if args.toc:
        cmd += ["--toc", f"--toc-depth={args.toc_depth}",
                "--metadata", "toc-title=目录"]
    r = subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8",
                       errors="replace")
    if r.returncode != 0:
        print(f"ERROR: pandoc failed:\n{r.stderr}", file=sys.stderr)
        return 1

    toc_entries = toc_dropped = 0
    if args.toc:
        page = html.read_text(encoding="utf-8")
        page, toc_entries, toc_dropped = tidy_toc(page)
        with open(html, "w", encoding="utf-8", newline="\n") as f:
            f.write(page)

    # HTML -> PDF. virtual-time-budget lets large embedded images finish
    # decoding before the page is printed. generate-pdf-document-outline
    # builds the bookmark tree from h1-h6; unknown switches are ignored by
    # older builds, so it is safe to pass unconditionally.
    out.parent.mkdir(parents=True, exist_ok=True)
    outline_flag = ["--generate-pdf-document-outline"] if args.toc else []
    for headless in ("--headless=new", "--headless"):
        r = subprocess.run([
            browser, headless, "--disable-gpu", "--no-sandbox",
            "--no-pdf-header-footer", "--virtual-time-budget=20000",
            *outline_flag,
            f"--print-to-pdf={out}", html.as_uri(),
        ], capture_output=True, text=True, encoding="utf-8", errors="replace",
            timeout=180)
        if out.exists():
            break

    if not out.exists():
        print("ERROR: browser produced no PDF.", file=sys.stderr)
        print((r.stderr or "")[-800:], file=sys.stderr)
        return 1

    pages = "?"
    outline = None
    try:
        import fitz
        with fitz.open(out) as d:
            pages = len(d)
            outline = len(d.get_toc())
    except Exception:
        pass

    if not args.keep_html:
        shutil.rmtree(tmp, ignore_errors=True)

    print(f"pdf    : {out}")
    print(f"size   : {out.stat().st_size / 1024 / 1024:.1f} MB")
    print(f"pages  : {pages}")
    print(f"font   : {args.font}")
    if not args.toc:
        print("toc    : off (--no-toc)")
    else:
        print(f"toc    : {toc_entries} entries (depth {args.toc_depth}"
              + (f", {toc_dropped} 图/表 headings excluded" if toc_dropped
                 else "") + ")")
        if outline == 0:
            print("outline: NONE - this browser ignored "
                  "--generate-pdf-document-outline; the 目录 page is still "
                  "there, but the PDF has no bookmark tree")
        elif outline:
            print(f"outline: {outline} bookmarks")
    return 0


if __name__ == "__main__":
    sys.exit(main())
